services:
  backend:
    build: ./
    container_name: backend_class
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env

  nginxproxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81" # panel de admin
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
